Optimize and clean up some scripts  On branch feature/v13_atmos_prep 	modified:   jobs/JGEFS_ATMOS_PREP 	modified:   parm/parm_gefs/gefs.parm 	modified:   rocoto/bin/hera/atmos_prep.sh 	modified:   rocoto/parm/gefs_config 	modified:   rocoto/parm/setbase 	modified:   rocoto/py/GEFS_XML_For_Tasks.py
Refs: #87

diff --git a/jobs/JGEFS_ATMOS_PREP b/jobs/JGEFS_ATMOS_PREP
--- a/jobs/JGEFS_ATMOS_PREP
+++ b/jobs/JGEFS_ATMOS_PREP
@@ -1,11 +1,11 @@
 #! /usr/bin/env bash
 
-source "${HOMEgfs:-${HOMEgefs}}/ush/preamble.sh"
+source "${HOMEgefs:-${HOMEgfs}}/ush/preamble.sh"
 
 ####################################
 # Determine Job Output Name on System
 ####################################
-export jobid=${jobid:-"$job.$PBS_JOBID"}
+export jobid=${jobid:-"${job}.${PBS_JOBID}"}
 export pgmout="OUTPUT.${PBS_JOBID}"
 export pgmerr=errfile
 
@@ -20,7 +20,7 @@ cd $DATA
 # Set up compute resources
 ######################################
 export total_tasks=${total_tasks:-36}  # Must be divisible number of tiles (6)
-export APRUN=${gefsmpexec:-"mpiexec -n $total_tasks"}
+export APRUN=${gefsmpexec:-"mpiexec -n ${total_tasks}"}
 
 ####################################
 # Specify NET and RUN Name and model
@@ -51,10 +51,10 @@ source PDY
 # Specify Execution Areas
 ####################################
 export HOMEgefs=${HOMEgefs:-${PACKAGEROOT}/gefs.${gefs_ver}}
-export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
-export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
-export USHgefs=${USHgefs:-$HOMEgefs/ush}
-export FIXgefs=${FIXgefs:-$HOMEgefs/fix/fix_gefs}
+export PARMgefs=${PARMgefs:-${HOMEgefs}/parm}
+export EXECgefs=${EXECgefs:-${HOMEgefs}/exec}
+export USHgefs=${USHgefs:-${HOMEgefs}/ush}
+export FIXgefs=${FIXgefs:-${HOMEgefs}/fix/fix_gefs}
 
 ##############################################
 # Define COM directories
@@ -68,21 +68,19 @@ export COMPONENT="atmos"
 configs="gefs gefs_atmos_prep"
 config_path=$PARMgefs/parm_gefs
 for config in $configs; do
-  . $config_path/$config.parm
+  . ${config_path}/${config}.parm
   export err=$?
   if [[ $err != 0 ]]; then
-    echo "FATAL ERROR in $(basename $BASH_SOURCE): Error while loading parm file $config_path/$config.parm"
-    exit $err
+    echo "FATAL ERROR in $(basename $BASH_SOURCE): Error while loading parm file ${config_path}/${config}.parm"
+    exit ${err}
   fi
 done
-
-export ROTDIR=${ROTDIR:-$(compath.py -o $NET/${ver})}
-export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/${cyc}}
 
 export COMINgfs=${COMINgfs:-$(compath.py ${envir}/com/gfs/${gfs_ver})/gfs.${PDY}/${cyc}}
 export COMINenkfgfs=${COMINenkfgfs:-$(compath.py ${envir}/com/gfs/${gfs_ver})/enkfgfs.${PDY}/${cyc}}
 
-NCP=${NCP:-"/bin/cp -p"}
+export ROTDIR=${ROTDIR:-$(compath.py -o $NET/${ver})}
+#export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/${cyc}}
 
 echo "Environment before calling script"
 env | sort
@@ -91,10 +89,10 @@ env | sort
 # Execute the script
 $HOMEgefs/scripts/exgefs_atmos_prep.sh
 export err=$?
-if [[ $err == 0 ]]; then
-  echo "$job completed normally!"
+if [[ ${err} == 0 ]]; then
+  echo "${job} completed normally!"
 else
-  echo "FATAL ERROR in $(basename $BASH_SOURCE): $job failed!"
+  echo "FATAL ERROR in $(basename $BASH_SOURCE): ${job} failed!"
   exit $err
 fi
 #############################################################
@@ -102,8 +100,8 @@ fi
 ##############################
 # Remove the Temporary working directory
 ##############################
-cd $DATAROOT
-if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
+cd ${DATAROOT}
+if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf ${DATA} ; fi
 
 echo "$(date -u) end $(basename $BASH_SOURCE)"
 
