Add previous changes for ensavg_netcdf
 On branch feature/v13_atmos_ensavg_netcdf
	modified:   ecf/def/gefs_prod00.def
	modified:   ecf/def/gefs_prod06.def
	modified:   ecf/def/gefs_prod12.def
	modified:   ecf/def/gefs_prod18.def
	modified:   ecf/post_processing/d0_16/atmos/jgefs_atmos_ensavg_netcdf.ecf
	modified:   jobs/JGEFS_ATMOS_ENSAVG_NETCDF
	modified:   rocoto/bin/hera/ensavg_netcdf.sh
	modified:   rocoto/bin/wcoss2/ensavg_netcdf.sh
	modified:   rocoto/py/GEFS_XML_For_Tasks.py
	modified:   rocoto/py/job_id.conf
	modified:   rocoto/py/user_hera.conf
	modified:   rocoto/py/user_wcoss2.conf
	modified:   scripts/exgefs_atmos_ensavg_netcdf.sh
	modified:   ush/gefs_ensavg_netcdf.sh

Refs: #96

diff --git a/jobs/JGEFS_ATMOS_ENSAVG_NETCDF b/jobs/JGEFS_ATMOS_ENSAVG_NETCDF
--- a/jobs/JGEFS_ATMOS_ENSAVG_NETCDF
+++ b/jobs/JGEFS_ATMOS_ENSAVG_NETCDF
@@ -1,13 +1,13 @@
-#!/bin/ksh
+#! /usr/bin/env bash
 
-echo "$(date -u) begin ${.sh.file}"
+echo "$(date -u) begin ${BASH_SOURCE}"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
-	# Turn on strict bash error checking
-	set -eu
+  # Turn on strict bash error checking
+  set -eu
 fi
-export PS4='$SECONDS + $(basename ${.sh.file})[$LINENO] '
+export PS4='$SECONDS + $(basename ${BASH_SOURCE})[$LINENO] '
 
 ####################################
 # Determine Job Output Name on System
@@ -67,19 +67,18 @@ export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
 ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
 export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${ver})/${RUN}.${PDY}/$cyc}
 export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc}
-
 #############################
 # Source relevant config files
 #############################
-configs="gefs gefs_atmos_ensavg_nemsio"
+configs="gefs gefs_atmos_ensavg_netcdf"
 config_path=$PARMgefs
 for config in $configs; do
-    . $config_path/$config.parm
-    export err=$?
-    if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
-        exit $err
-    fi
+  . $config_path/$config.parm
+  export err=$?
+  if [[ $err != 0 ]]; then
+    echo "FATAL ERROR in ${BASH_SOURCE}: Error while loading parm file $config_path/$config.parm"
+    exit $err
+  fi
 done
 
 export COMPONENT=${COMPONENT:-atmos}
@@ -89,13 +88,13 @@ env | sort
 
 #############################################################
 # Execute the script
-$HOMEgefs/scripts/exgefs_atmos_ensavg_nemsio.sh
+$HOMEgefs/scripts/exgefs_atmos_ensavg_netcdf.sh
 export err=$?
 if [[ $err == 0 ]]; then
-    echo "$job completed normally!"
+  echo "$job completed normally!"
 else
-    echo "FATAL ERROR in ${.sh.file}: $job failed!"
-    exit $err
+  echo "FATAL ERROR in ${BASH_SOURCE}: $job failed!"
+  exit $err
 fi
 #############################################################
 
@@ -105,6 +104,6 @@ fi
 cd $DATAROOT
 if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
 
-echo "$(date -u) end ${.sh.file}"
+echo "$(date -u) end ${BASH_SOURCE}"
 
 exit $err
