Change {0} back to ${.sh.file} and $BASH_SOURCE
in j-job, ush scripts and ex-scripts

 On branch feature/ops_port2wcoss2

Refs: #23

diff --git a/jobs/JGEFS_ATMOS_POST_CLEANUP b/jobs/JGEFS_ATMOS_POST_CLEANUP
--- a/jobs/JGEFS_ATMOS_POST_CLEANUP
+++ b/jobs/JGEFS_ATMOS_POST_CLEANUP
@@ -8,14 +8,14 @@
 # 05/07/2020 Xianwu Xue, Modify it for GEFS v12
 ######################################################################
 
-echo "$(date -u) begin ${0}"
+echo "$(date -u) begin ${.sh.file}"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
 	# Turn on strict bash error checking
 	set -eu
 fi
-export PS4='$SECONDS + $(basename ${0})[$LINENO] '
+export PS4='$SECONDS + $(basename ${.sh.file})[$LINENO] '
 
 ####################################
 # Determine Job Output Name on System
@@ -85,8 +85,8 @@ for config in $configs; do
     . $config_path/$config.parm
     export err=$?
     if [[ $err != 0 ]]; then
-    	echo "FATAL ERROR in ${0}: Error while loading parm file $config_path/$config.parm"
-    	exit $err
+        echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path/$config.parm"
+        exit $err
     fi
 done
 export COMPONENT="atmos"
@@ -101,7 +101,7 @@ export err=$?
 if [[ $err == 0 ]]; then
     echo "$job completed normally!"
 else
-    echo "FATAL ERROR in ${0}: $job failed!"
+    echo "FATAL ERROR in ${.sh.file}: $job failed!"
     exit $err
 fi
 #############################################################
@@ -112,7 +112,7 @@ fi
 cd $DATAROOT
 if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
 
-echo "$(date -u) end ${0}"
+echo "$(date -u) end ${.sh.file}"
 
 exit $err
 
