Clean j-job and error messages for prep_emissions
Remakes the j-job to NCO standards. Places where jid ($$) were
used are replaced with $LSB_JOBID. Some settings are pushed down
to the parm file.

Additionally, a lot of output and error checking is standardized,
including the PS4 and error messages.

Refs: #63941, #76266

diff --git a/jobs/JGEFS_CHEM_PREP_EMISSIONS b/jobs/JGEFS_CHEM_PREP_EMISSIONS
--- a/jobs/JGEFS_CHEM_PREP_EMISSIONS
+++ b/jobs/JGEFS_CHEM_PREP_EMISSIONS
@@ -1,27 +1,25 @@
-#!/bin/ksh 
+#!/bin/bash
 
-echo $(date) $0 $(date -u) begin
+echo "$(date) $0 $(date -u) begin"
 
 set -xa
-export PS4='$SECONDS + '
-date
-
-export total_tasks=${total_tasks:-1}
-export gefsmpexec=${gefsmpexec:-"mpirun -n $total_tasks"}
-export APRUN=${gefsmpexec:-"mpirun -n $total_tasks"}
-
-export RUNMEM=${RUNMEM:-geaer}
-export mem=$(echo $RUNMEM|cut -c3-5)
-export ENS_NUM=1
-echo "ENS_NUM=$ENS_NUM"
-
-export COMPONENT=chem
+if [[ ${STRICT:-NO} == "YES" ]]; then
+	# Turn on strict bash error checking
+	set -eu
+fi
+export PS4='$SECONDS + $(basename $0)[$LINENO] '
 
 ####################################
-# obtain unique process id (pid) and make working directory
+# Determine Job Output Name on System
 ####################################
-export pid=$$
-export DATA=${DATA:-$DATAROOT/${job}.${pid}}
+export jobid=${jobid:-"$job.$LSB_JOBID"}
+export pgmout="OUTPUT.${LSB_JOBID}"
+export pgmerr=errfile
+
+####################################
+# Specify and create working directory
+####################################
+export DATA=${DATA:-${DATAROOT}/${jobid}}
 mkdir -p $DATA
 cd $DATA
 
@@ -29,98 +27,67 @@ cd $DATA
 # Specify NET and RUN Name and model
 ####################################
 export NET=${NET:-gefs}
+export envir=${envir:-prod}
 export RUN=${RUN:-gefs}
 
-####################################
-# File To Log Msgs
-####################################
-export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}
-
-############################
-# Set up cycle varaible
-############################
-export cycle=${cycle:-t${cyc}z}
-export CDATE=$PDY$cyc
-
-####################################
-# Determine Job Output Name on System
-####################################
-export outid="LL$job"
-export jobid="${outid}.o${pid}"
-export pgmout="OUTPUT.${pid}"
-export pgmerr=errfile
-
-####################################
+######################################
 # SENDCOM  - Copy Files From TMPDIR to $COMOUT
 # SENDDBN  - Issue DBNet Client Calls
 # SENDECF  - Flag Events on ECF
 # VERBOSE  - Specify Verbose Output
-####################################
+######################################
 export SENDCOM=${SENDCOM:-YES}
 export SENDDBN=${SENDDBN:-YES}
 export SENDECF=${SENDECF:-YES}
 export VERBOSE=${VERBOSE:-YES}
 
+######################################
+# Set up the date information
+######################################
+export cycle=t${cyc}z
+setpdy.sh
+source PDY
+
 ####################################
 # Specify Execution Areas
 ####################################
-export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
-export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
+export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}
 export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
 
-export HOMEgfs=${HOMEgfs:-${HOMEgefs}}
-export PARMgfs=$HOMEgfs/parm
-export FIXgfs=$HOMEgfs/fix
-export USHgfs=$HOMEgfs/ush
-export UTILgfs=$HOMEgfs/util
-export EXECgfs=$HOMEgfs/exec
-export SCRgfs=$HOMEgfs/scripts
-
-export HOMEchem=${HOMEchem:-$HOMEgfs}
-export PARMchem=${PARMchem:-$HOMEchem/parm}
-export EXECchem=${EXECchem:-$HOMEchem/exec}
-export FIXchem=${FIXchem:-$FIXgfs/fix_chem}
-
-####################################
-# Run setpdy and initialize PDY variables
-####################################
-setpdy.sh
-. ./PDY
-
 ##############################################
-echo "set parameters using gefs.parm"
+# Define COM directories
 ##############################################
-. $PARMgefs/gefs.parm
-. $PARMgefs/gefs_prep_emissions.parm
+export COMPONENT=chem
+export GESOUT=$GESROOT/${envir}/${RUN}.${PDY}/$cyc
+mkdir -p $GESOUT
 
-export CDUMP=${CDUMP:-gfs} 
+#############################
+# Source relevant config files
+#############################
+configs="gefs gefs_prep_emissions"
+config_path=$PARMgefs
+for config in $configs; do
+    . $config_path/$config.parm
+    err=$?
+    if [[ $err != 0 ]]; then
+    	echo "FATAL ERROR in $0: Error while loading parm file $config_path"
+    	exit $err
+    fi
+done
 
-##############################################
-# Define COM OUT directories
-##############################################
-export COMOUT=${COMOUT:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}}/$cyc/$COMPONENT
-export GESIN=$GESROOT/${envir}/${RUN}.${PDY}/$cyc
-export COMOUTchem=${COMOUTchem:-$GESIN/$mem}
-export CHEM_OUTPUT_FORMAT=${CHEM_OUTPUT_FORMAT:-chem/tile%TILE%/%INPUT%.dat}
-export CASE=${CASEHR:-C384}
-##############################################
-echo "list environment before running script"
-##############################################
-
+echo "Environment before calling script"
 env | sort
 
 #############################################################
 # Execute the script
-$gefsmpexec $HOMEchem/scripts/exglobal_prep_chem.bash
-#############################################################
+$HOMEchem/scripts/exglobal_prep_chem.bash
 err=$?
-
-if [ $err = 0 ]; then
-    msg="$job completed normally!"
+if [[ $err == 0 ]]; then
+    echo "$job completed normally!"
 else
-    msg="FATAL ERROR: $job failed!"
+    echo "FATAL ERROR: $job failed!"
 fi
-postmsg "$jlogfile" "$msg"
+#############################################################
 
 ##############################
 # Remove the Temporary working directory
@@ -131,4 +98,3 @@ if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
 echo "$(date) $0 $(date -u) end"
 
 exit $err
-
