Clean j-job and error messages for chem_init
Remakes the j-job to NCO standards. Places where jid ($$) were
used are replaced with $LSB_JOBID. Some settings are pushed down
to a new parm file. There is also a small amount of setting
shuffling between parm files.

Also updated the python script to conform to bash variables more
and provide better error messages. This includes using mail.py to
email when it fails to produce an increment for warm start to warn
that the forecast may be degraded.

Additionally, a lot of output and error checking is standardized,
including the PS4 and error messages.

Refs: #63941, #76266

diff --git a/jobs/JGEFS_CHEM_INIT b/jobs/JGEFS_CHEM_INIT
--- a/jobs/JGEFS_CHEM_INIT
+++ b/jobs/JGEFS_CHEM_INIT
@@ -1,123 +1,103 @@
-#!/bin/ksh 
+#!/bin/bash
 
-echo $(date) $0 $(date -u) begin
+echo "$(date) $0 $(date -u) begin"
 
 set -xa
-export PS4='$SECONDS + '
-date
-
-export APRUN_CALCINC=${APRUN_CALCINC:-"mpirun -n 1"}
-export APRUN_CHGRES=${APRUN_CHGRES:-"mpirun -n 1"}
-
-export COMPONENT=chem
-export AEROSOL_INIT_TYPE=${AEROSOL_INIT_TYPE:-warm}
+if [[ ${STRICT:-NO} == "YES" ]]; then
+	# Turn on strict bash error checking
+	set -eu
+fi
+export PS4='$SECONDS + $(basename $0)[$LINENO] '
 
 ####################################
-# obtain unique process id (pid) and make working directory
+# Determine Job Output Name on System
 ####################################
-export pid=$$
-export DATA=${DATA:-${DATAROOT}/${job}.${pid}}
+export jobid=${jobid:-"$job.$LSB_JOBID"}
+export pgmout="OUTPUT.${LSB_JOBID}"
+export pgmerr=errfile
+
+####################################
+# Specify and create working directory
+####################################
+export DATA=${DATA:-${DATAROOT}/${jobid}}
 mkdir -p $DATA
 cd $DATA
 
-############################
-# Set up cycle varaible
-############################
-export cycle=${cycle:-t${cyc}z}
+######################################
+# Set up compute resources
+######################################
+export APRUN_CALCINC=${APRUN_CALCINC:-"mpirun -n 1"}
+export APRUN_CHGRES=${APRUN_CHGRES:-"mpirun -n 1"}
 
 ####################################
 # Specify NET and RUN Name and model
 ####################################
 export NET=${NET:-gefs}
+export envir=${envir:-prod}
 export RUN=${RUN:-gefs}
 
-####################################
-# File To Log Msgs
-####################################
-export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}
-
-###########################
-# Set up cycle varaible
-############################
-export cycle=${cycle:-t${cyc}z}
-export CDATE=$PDY$cyc
-
-####################################
-# Determine Job Output Name on System
-####################################
-export outid="LL$job"
-export jobid="${outid}.o${pid}"
-export pgmout="OUTPUT.${pid}"
-export pgmerr=errfile
-
-####################################
+######################################
 # SENDCOM  - Copy Files From TMPDIR to $COMOUT
 # SENDDBN  - Issue DBNet Client Calls
 # SENDECF  - Flag Events on ECF
 # VERBOSE  - Specify Verbose Output
-####################################
+######################################
 export SENDCOM=${SENDCOM:-YES}
 export SENDDBN=${SENDDBN:-YES}
 export SENDECF=${SENDECF:-YES}
 export VERBOSE=${VERBOSE:-YES}
 
+######################################
+# Set up the date information
+######################################
+export cycle=t${cyc}z
+setpdy.sh
+source PDY
+
 ####################################
 # Specify Execution Areas
 ####################################
-export HOMEgefs=${HOMEgefs:-$NWROOT/gefs.${gefs_ver}}
+export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}
 export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
 
-export HOMEgfs=${HOMEgfs:-${HOMEgefs}}
-export FIXgfs=$HOMEgfs/fix
-export USHgfs=$HOMEgfs/ush
-
-export REGRIDEXEC=${REGRIDEXEC:-$HOMEgfs/exec/chgres_recenter.exe}
-export CALCINCEXEC=${CALCINCEXEC:-$HOMEgfs/exec/calc_increment_ens_gsdchem.x}
-
-##############################
-# Run setpdy and initialize PDY variables
-##############################
-setpdy.sh
-. PDY
-
 ##############################################
-echo "set parameters using gefs.parm"
+# Define COM directories
 ##############################################
-. $PARMgefs/gefs.parm
-. $PARMgefs/gefs_fcst.parm
-
-##############################################
-# Define COM OUT directories
-##############################################
-export COMINgfs=${COMINgfs:-$(compath.py gfs/prod)/gfs.${PDY}/$cyc}
-export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}}/$cyc/atmos/init
-export COMOUT=${COMOUT:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}}/$cyc/$COMPONENT/init
+export COMPONENT=chem
+export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/$cyc/$COMPONENT}
+# Note: COMROOT is also used in child script to search for COMIN from previous cycles
 export GESIN=$GESROOT/${envir}/${RUN}.${PDY}/$cyc
+export GESOUT=$GESROOT/${envir}/${RUN}.${PDY}/$cyc
 
-if [[ $SENDCOM == "YES" ]]; then
-	mkdir -p $COMOUT
-fi
+export COMINgfs=${COMINgfs:-$(compath.py gfs/prod)/gfs.${PDY}/$cyc}
 
-export gefs_cych=${gefs_cych:-6}
+#############################
+# Source relevant config files
+#############################
+configs="gefs gefs_chem_init"
+config_path=$PARMgefs
+for config in $configs; do
+    . $config_path/$config.parm
+    err=$?
+    if [[ $err != 0 ]]; then
+    	echo "FATAL ERROR in $0: Error while loading parm file $config_path"
+    	exit $err
+    fi
+done
 
-##############################################
-echo "list environment before running script"
-##############################################
-
+echo "Environment before calling script"
 env | sort
 
 #############################################################
 # Execute the script
 $HOMEgefs/scripts/exgefs_init_aerosol.py
-#############################################################
 err=$?
-
-if [ $err = 0 ]; then
-    msg="$job completed normally!"
+if [[ $err == 0 ]]; then
+    echo "$job completed normally!"
 else
-    msg="FATAL ERROR: $job failed!"
+    echo "FATAL ERROR: $job failed!"
 fi
-postmsg "$jlogfile" "$msg"
+#############################################################
 
 ##############################
 # Remove the Temporary working directory
@@ -128,4 +108,3 @@ if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
 echo "$(date) $0 $(date -u) end"
 
 exit $err
-
