Add an exit on error before $DATA is deleted
Changed the j-jobs so that they exit if scripts return an error
without deleting the $DATA directory even if $KEEPDATA is NO.

Refs: #63941, #76266

diff --git a/jobs/JGEFS_CHEM_PREP_EMISSIONS b/jobs/JGEFS_CHEM_PREP_EMISSIONS
--- a/jobs/JGEFS_CHEM_PREP_EMISSIONS
+++ b/jobs/JGEFS_CHEM_PREP_EMISSIONS
@@ -85,7 +85,8 @@ err=$?
 if [[ $err == 0 ]]; then
     echo "$job completed normally!"
 else
-    echo "FATAL ERROR: $job failed!"
+    echo "FATAL ERROR in ${.sh.file}: $job failed!"
+    exit $err
 fi
 #############################################################
 
diff --git a/jobs/JGEFS_WAVE_POST b/jobs/JGEFS_WAVE_POST
--- a/jobs/JGEFS_WAVE_POST
+++ b/jobs/JGEFS_WAVE_POST
@@ -99,7 +99,8 @@ err=$?
 if [[ $err == 0 ]]; then
     echo "$job completed normally!"
 else
-    echo "FATAL ERROR: $job failed!"
+    echo "FATAL ERROR in $(basename $BASH_SOURCE): $job failed!"
+    exit $err
 fi
 #############################################################
 
