Modify compath.py format in j-jobs
 On branch feature/ops_port2wcoss2
 Changes to be committed:
	modified:   jobs/JGEFS_ATMOS_GEMPAK_META
	modified:   jobs/JGEFS_ATMOS_GETCFSSST
	modified:   jobs/JGEFS_ATMOS_POST
	modified:   jobs/JGEFS_ATMOS_PRDGEN
	modified:   jobs/JGEFS_ATMOS_PREP
	new file:   jobs/JGEFS_ATMOS_PREP_new
	modified:   jobs/JGEFS_CHEM_INIT
	new file:   jobs/JGEFS_FORECAST_new
	modified:   jobs/JGEFS_WAVE_PREP

Refs: #23

diff --git a/jobs/JGEFS_ATMOS_PREP_new b/jobs/JGEFS_ATMOS_PREP_new
--- a/jobs/JGEFS_ATMOS_PREP_new
+++ b/jobs/JGEFS_ATMOS_PREP_new
@@ -12,24 +12,24 @@ export PS4='$SECONDS + $(basename $(basename ${0}))[$LINENO] '
 ####################################
 # Determine Job Output Name on System
 ####################################
-export jobid=${jobid:-"$job.$LSB_JOBID"}
-export pgmout="OUTPUT.${LSB_JOBID}"
+export jobid=${jobid:-"$job.$PBS_JOBID"}
+export pgmout="OUTPUT.${PBS_JOBID}"
 export pgmerr=errfile
-
-######################################
-# Set up compute resources
-######################################
-export wavempexec=${wavempexec:-"mpirun -n"}
-export wave_mpmd=${wave_mpmd:-"cfp"}
-export NTASKS=${total_tasks:-16}
 
 ####################################
 # Specify and create working directory
 ####################################
 export DATA=${DATA:-${DATAROOT}/${jobid}}
 mkdir -p $DATA
-mkdir $DATA/INPUT
 cd $DATA
+
+######################################
+# Set up compute resources
+######################################
+export total_tasks=${total_tasks:-36}  # Must be divisible number of tiles (6)
+export APRUN=${gefsmpexec:-""} #mpiexec –n $total_tasks –ppn $total_tasks --cpu-bind core --depth=6 "}
+# "mpiexec –n $total_tasks –ppn $total_tasks --cpu-bind core "}
+#mpirun -n $total_tasks"}
 
 ####################################
 # Specify NET and RUN Name and model
@@ -59,53 +59,45 @@ source PDY
 ####################################
 # Specify Execution Areas
 ####################################
-export HOMEgefs=${HOMEgefs:-${PACKAGEROOT}/gefs.${gefs_ver}}
-export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
+export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}
 export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
-export FIXwave=${FIXwave:-$HOMEgefs/fix/fix_wave}
+export EXECgefs=${EXECgefs:-$HOMEgefs/exec}
+export USHgefs=${USHgefs:-$HOMEgefs/ush}
+export FIXgefs=${FIXgefs:-$HOMEgefs/fix/fix_gefs}
 
 ##############################################
 # Define COM directories
 ##############################################
-# Have to include $COMPONENT in COM paths for downstream scripts
-ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
-export COMIN=$COMROOT/${NET}/${ver}/${RUN}.${PDY}/$cyc/wave
-export COMOUT=$COMROOT/${NET}/${ver}/${RUN}.${PDY}/$cyc/wave
-if [[ $SENDCOM = YES ]]; then
-  mkdir -p $COMOUT/rundata
-fi
-
-export COMINgfs=${COMINgfs:-$(compath.py canned/com/gfs/${ver_gfs})/gfs.${PDY}/${cyc}/atmos}
-export COMIN_WAV_ICE=${COMINgfs:-$(compath.py canned/com/gfs/${ver_gfs})/${WAVICEPRFX:-gfs}.${PDY}/${cyc}/atmos}
+export COMPONENT="atmos"
+export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/$cyc/$COMPONENT}
+export GESOUT=$GESROOT/${envir}/${RUN}.${PDY}/$cyc
 
 #############################
 # Source relevant config files
 #############################
-configs="gefs gefs_wave gefs_wave_prep"
+configs="gefs gefs_atmos_prep"
 config_path=$PARMgefs
-
 for config in $configs; do
     . $config_path/$config.parm
     export err=$?
-    if [[ $err -ne 0 ]]; then
-    	echo "FATAL ERROR in $(basename ${0}): Error while loading parm file $config_path/$config.parm"
-    	exit $err
+    if [[ $err != 0 ]]; then
+        echo "FATAL ERROR in $(basename ${0}): Error while loading parm file $config_path/$config.parm"
+        exit $err
     fi
 done
 
-export errchk=${errchk:-err_chk}
-if [[ $SENDCOM == "YES" ]]; then
-    export wavelog=${COMOUT}/wave.log
-else
-    export wavelog=${DATA}/wave.log
-fi
+export COMINgfs=${COMINgfs:-$(compath.py canned/com/gfs/${ver_gfs})/gfs.${PDY}/${cyc}/atmos}
+export COMINenkf=${COMINenkf:-$(compath.py canned/com/gfs/${ver_gfs})/enkfgdas.${pdyp}/${cycp}/atmos}
+
+NCP=${NCP:-"/bin/cp -p"}
+export jlogfile=${jlogfile:-$DATA/jlogfile}
 
 echo "Environment before calling script"
 env | sort
 
 #############################################################
 # Execute the script
-$HOMEwave/scripts/exwave_prep.sh
+$HOMEgefs/scripts/exgefs_atmos_prep.sh
 export err=$?
 if [[ $err == 0 ]]; then
     echo "$job completed normally!"
@@ -124,3 +116,4 @@ if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
 echo "$(date -u) end $(basename ${0})"
 
 exit $err
+
