Port task chem_prep_emissions to WCOSS2/Acorn
 On branch feature/ops_port2wcoss2
	modified:   jobs/JGEFS_CHEM_PREP_EMISSIONS
	modified:   rocoto/dev/lsf/wcoss2/chem/jgefs_chem_prep_emissions.ecf

Refs: #23

diff --git a/jobs/JGEFS_CHEM_PREP_EMISSIONS b/jobs/JGEFS_CHEM_PREP_EMISSIONS
--- a/jobs/JGEFS_CHEM_PREP_EMISSIONS
+++ b/jobs/JGEFS_CHEM_PREP_EMISSIONS
@@ -1,19 +1,19 @@
 #!/bin/bash
 
-echo "$(date -u) begin $(basename $BASH_SOURCE)"
+echo "$(date -u) begin $(basename ${0})"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
 	# Turn on strict bash error checking
 	set -eu
 fi
-export PS4='$SECONDS + $(basename $BASH_SOURCE))[$LINENO] '
+export PS4='$SECONDS + $(basename ${0}))[$LINENO] '
 
 ####################################
 # Determine Job Output Name on System
 ####################################
-export jobid=${jobid:-"$job.$LSB_JOBID"}
-export pgmout="OUTPUT.${LSB_JOBID}"
+export jobid=${jobid:-"$job.$PBS_JOBID"}
+export pgmout="OUTPUT.${PBS_JOBID}"
 export pgmerr=errfile
 
 ####################################
@@ -70,8 +70,8 @@ for config in $configs; do
     . $config_path/$config.parm
     export err=$?
     if [[ $err != 0 ]]; then
-    	echo "FATAL ERROR in $(basename $BASH_SOURCE): Error while loading parm file $config_path/$config.parm"
-    	exit $err
+        echo "FATAL ERROR in $(basename ${0}): Error while loading parm file $config_path/$config.parm"
+        exit $err
     fi
 done
 
@@ -87,7 +87,7 @@ export err=$?
 if [[ $err == 0 ]]; then
     echo "$job completed normally!"
 else
-    echo "FATAL ERROR in $(basename $BASH_SOURCE): $job failed!"
+    echo "FATAL ERROR in $(basename ${0}): $job failed!"
     exit $err
 fi
 #############################################################
@@ -98,6 +98,6 @@ fi
 cd $DATAROOT
 if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
 
-echo "$(date -u) end $(basename $BASH_SOURCE)"
+echo "$(date -u) end $(basename ${0})"
 
 exit $err
