Add some changes for atmos_prep in the pre develop  On branch feature/v13_atmos_prep 	modified:   jobs/JGEFS_ATMOS_PREP 	modified:   rocoto/bin/wcoss2/atmos_prep.sh 	modified:   rocoto/bin/wcoss2/common.sh 	modified:   rocoto/py/GEFS_XML_For_Tasks.py 	modified:   scripts/exgefs_atmos_prep.sh 	modified:   ush/gefs_atmos_prep.sh
Refs: #87

diff --git a/jobs/JGEFS_ATMOS_PREP b/jobs/JGEFS_ATMOS_PREP
--- a/jobs/JGEFS_ATMOS_PREP
+++ b/jobs/JGEFS_ATMOS_PREP
@@ -4,8 +4,8 @@ echo "$(date -u) begin $(basename $BASH_SOURCE)"
 
 set -xa
 if [[ ${STRICT:-NO} == "YES" ]]; then
-	# Turn on strict bash error checking
-	set -eu
+  # Turn on strict bash error checking
+  set -eu
 fi
 export PS4='$SECONDS + $(basename $(basename $BASH_SOURCE))[$LINENO] '
 
@@ -68,24 +68,25 @@ export FIXgefs=${FIXgefs:-$HOMEgefs/fix/fix_gefs}
 ##############################################
 ver=${ver:-$(echo ${gefs_ver}|cut -c1-5)}
 export COMPONENT="atmos"
-export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc/$COMPONENT}
-export GESOUT=${GESOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/$cyc/nwges}
+
 #############################
 # Source relevant config files
 #############################
 configs="gefs gefs_atmos_prep"
 config_path=$PARMgefs
 for config in $configs; do
-    . $config_path/$config.parm
-    export err=$?
-    if [[ $err != 0 ]]; then
-        echo "FATAL ERROR in $(basename $BASH_SOURCE): Error while loading parm file $config_path/$config.parm"
-        exit $err
-    fi
+  . $config_path/$config.parm
+  export err=$?
+  if [[ $err != 0 ]]; then
+    echo "FATAL ERROR in $(basename $BASH_SOURCE): Error while loading parm file $config_path/$config.parm"
+    exit $err
+  fi
 done
 
-export COMINgfs=${COMINgfs:-$(compath.py ${envir}/com/gfs/${gfs_ver})/gfs.${PDY}/${cyc}/atmos}
-export COMINenkf=${COMINenkf:-$(compath.py ${envir}/com/gfs/${gfs_ver})/enkfgdas.${pdyp}/${cycp}/atmos}
+export COMOUT=${COMOUT:-$(compath.py -o $NET/${ver})/${RUN}.${PDY}/${cyc}}
+
+export COMINgfs=${COMINgfs:-$(compath.py ${envir}/com/gfs/${gfs_ver})/gfs.${PDY}/${cyc}}
+export COMINenkfgfs=${COMINenkfgfs:-$(compath.py ${envir}/com/gfs/${gfs_ver})/enkfgfs.${PDY}/${cyc}}
 
 NCP=${NCP:-"/bin/cp -p"}
 
@@ -97,10 +98,10 @@ env | sort
 $HOMEgefs/scripts/exgefs_atmos_prep.sh
 export err=$?
 if [[ $err == 0 ]]; then
-    echo "$job completed normally!"
+  echo "$job completed normally!"
 else
-    echo "FATAL ERROR in $(basename $BASH_SOURCE): $job failed!"
-    exit $err
+  echo "FATAL ERROR in $(basename $BASH_SOURCE): $job failed!"
+  exit $err
 fi
 #############################################################
 
