Clean j-job and error messages for postsnd
Remakes the j-job to NCO standards. Places where jid ($$) were used are
replaced with $LSB_JOBID. A new parm file is created to hold some of the
settings formerly in the j-job. Others settings are pushed down to the
scripts-level.

Additionally, a lot of output and error checking is standardized,
including the PS4 and error messages.

Refs: #63941, #76266

diff --git a/jobs/JGEFS_ATMOS_POSTSND b/jobs/JGEFS_ATMOS_POSTSND
--- a/jobs/JGEFS_ATMOS_POSTSND
+++ b/jobs/JGEFS_ATMOS_POSTSND
@@ -1,181 +1,109 @@
-#!/bin/sh
+#!/bin/ksh
 
-echo $(date) $0 $(date -u) begin
+echo "$(date -u) begin ${.sh.file}"
 
 set -xa
-export PS4='$SECONDS + '
-date
-export MODEL_OUT_FORM=binarynemsiompiio
-
-export total_tasks=${total_tasks:-10}
-export gefsmpexec=${gefsmpexec:-"mpirun -n $total_tasks"}
-export gefsmpexec_mpmd=${gefsmpexec_mpmd:-"mpirun -n $total_tasks cfp mpmd_cmdfile"}
-export APRUN_POSTSND=${gefsmpexec:-"mpirun -n $total_tasks"}
-export APRUN_POSTSNDCFP=${gefsmpexec_mpmd:-"mpirun -n $total_tasks cfp"}
-export machine=${machine:-"WCOSS_DELL_P3"}
-
-########################################
-# Runs GFS BUFR SOUNDINGS
-########################################
-
-############################
-export MP_EUIDEVELOP=min
-export KMP_STACKSIZE=2048m
-export MPICH_ALLTOALL_THROTTLE=0
-export MP_SINGLE_THREAD=yes
-export MP_EAGER_LIMIT=65536
-export MP_USE_BULK_XFER=no
-export MP_COLLECTIVE_OFFLOAD=no
-export MP_SHARED_MEMORY=yes
-export MP_MPILIB=mpich2
-export MP_LABELIO=yes
+if [[ ${STRICT:-NO} == "YES" ]]; then
+	# Turn on strict bash error checking
+	set -eu
+fi
+export PS4='$SECONDS + $(basename ${.sh.file})[$LINENO] '
 
 ####################################
-# obtain unique process id (pid) and make temp directory
-###################################
-export pid=$$
-export DATA=${DATA:-${DATAROOT}/${job}.${pid}}
+# Determine Job Output Name on System
+####################################
+export jobid=${jobid:-"$job.$LSB_JOBID"}
+export pgmout="OUTPUT.${LSB_JOBID}"
+export pgmerr=errfile
+
+####################################
+# Specify and create working directory
+####################################
+export DATA=${DATA:-${DATAROOT}/${jobid}}
 mkdir -p $DATA
 cd $DATA
 
-# Define MASTERRES for master file grid, default being Gaussian with alternatives of  p125/p25/p5
-export mem=$(echo $RUNMEM|cut -c3-5)
-
 ######################################
-# Set up the cycle variable
+# Set up compute resources
 ######################################
-export cycle=t${cyc}z
+export total_tasks=${total_tasks:-10}
+export APRUN=${gefsmpexec:-"mpirun -n $total_tasks"}
+export APRUN_MPMD=${gefsmpexec_mpmd:-"mpirun -n $total_tasks cfp"}
 
 ####################################
 # Specify NET and RUN Name and model
 ####################################
 export NET=${NET:-gefs}
+export envir=${envir:-prod}
 export RUN=${RUN:-gefs}
-export model=${model:-gfs}
 
-####################################
-# File To Log Msgs
-####################################
-export jlogfile=${jlogfile:-${DATA}/jlogfile.${job}.${pid}}
-
-####################################
-# Determine Job Output Name on System
-####################################
-export outid="LL$job"
-export jobid="${outid}.o${pid}"
-export pgmout="OUTPUT.${pid}"
-export pgmerr=errfile
-
-####################################
+######################################
 # SENDCOM  - Copy Files From TMPDIR to $COMOUT
 # SENDDBN  - Issue DBNet Client Calls
 # SENDECF  - Flag Events on ECF
 # VERBOSE  - Specify Verbose Output
-####################################
+######################################
 export SENDCOM=${SENDCOM:-YES}
 export SENDDBN=${SENDDBN:-YES}
-export SENDDBN=${SENDDBN_NTC:-YES}
 export SENDECF=${SENDECF:-YES}
 export VERBOSE=${VERBOSE:-YES}
 
-# Specify Execution Areas
-export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}
-export USHgefs=${USHgefs:-$HOMEgefs/ush}
-export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
-
-export HOMEpost=${HOMEpost:-${HOMEgefs}}
-
-export HOMEgfs=${HOMEgfs:-$HOMEgefs}
-
-###################################
-# Set up the UTILITIES
-###################################
-
-export HOMEbufrsnd=${HOMEgfs:-$HOMEgefs}
-export EXECbufrsnd=${EXECgfs:-$HOMEgfs/exec}
-export FIXbufrsnd=${FIXgfs:-$HOMEgfs/fix/product}
-export PARMbufrsnd=${PARMgfs:-$HOMEgfs/parm/product}
-export USHbufrsnd=${USHgfs:-$HOMEgfs/ush}
-export SCRbufrsnd=${SCRgfs:-$HOMEgfs/scripts}
-
-# Run setpdy and initialize PDY variables
+######################################
+# Set up the date information
+######################################
+export cycle=t${cyc}z
 setpdy.sh
-. ./PDY
+source PDY
 
-##############################
-# Define COM Directories
-##############################
-export COMIN=${COMIN:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}/${cyc}/atmos}
-export COMOUT=${COMOUT:-$COMROOT/${NET}/${envir}/${RUN}.${PDY}/${cyc}/atmos}
-export pcom=${pcom:-${COMOUT}/wmo}
-export COMAWP=${COMAWP:-${COMOUT}/gempak}
-mkdir -p $COMOUT $pcom $COMAWP
+####################################
+# Specify Execution Areas
+####################################
+export HOMEgefs=${HOMEgefs:-${NWROOT}/gefs.${gefs_ver}}
+export PARMgefs=${PARMgefs:-$HOMEgefs/parm}
+export USHgefs=${USHgefs:-$HOMEgefs/ush}
 
-if [ -e $COMOUT/bufr/$mem ]; then
-    rm -rf $COMOUT/bufr/$mem
-fi
-mkdir -m 775 -p $COMOUT/bufr/$mem
-mkdir -m 775 -p $COMOUT/misc/bufr
+##############################################
+# Define COM directories
+##############################################
+export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/$cyc}
+export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}/$cyc}
 
-############################################
-# Run gefs.parm to get input variables
-############################################
-. $PARMgefs/gefs.parm
+#############################
+# Source relevant config files
+#############################
+configs="gefs gefs_postsnd"
+config_path=$PARMgefs
+for config in $configs; do
+    . $config_path/$config.parm
+    err=$?
+    if [[ $err != 0 ]]; then
+    	echo "FATAL ERROR in ${.sh.file}: Error while loading parm file $config_path"
+    	exit $err
+    fi
+done
 
-export FHMAX_HF=$FHMAXHF
-export FHOUT_HF=$FHOUTHF
-export FHOUT=$FHOUTLF
+export COMPONENT=${COMPONENT:-atmos}
 
-export JCAP=${JCAPFV:-766}
-export LEVS=${LEVSHR:-64}
-export LATB=${LATBFV:-768}
-export LONB=${LONBFV:-1536}
-
-export STARTHOUR=${STARTHOUR:-00}
-export ENDHOUR=${ENDHOUR:-180}
-if (( ENDHOUR > fhmaxh )); then
-        export ENDHOUR=$fhmaxh
-fi
-
-export NINT3=$FHOUTLF     ##second period time interval
-export NZERO=6
-export NEND1=${NEND1:-${FHMAXHF}}   ##first period length with time interval = NINT1
-export NINT1=$FHOUTHF 
-
-if (( NEND1 >= ENDHOUR )); then
-        export NEND1=$ENDHOUR
-fi
-
-export INCREMENT=12
-export OUTFILE=meteomrf
-export MAKEBUFR=NO
-export F00FLAG=YES
-
-env
+echo "Environment before calling script"
+env | sort
 
 #############################################################
-# Execute the script.
+# Execute the script
 $HOMEgefs/scripts/exgefs_postsnd.sh.ecf
-#############################################################
 err=$?
-
-if [ $err = 0 ]; then
-    msg="$job completed normally!"
+if [[ $err == 0 ]]; then
+    echo "$job completed normally!"
 else
-    msg="FATAL ERROR: $job failed!"
+    echo "FATAL ERROR in ${.sh.file}: $job failed!"
 fi
-postmsg "$jlogfile" "$msg"
+#############################################################
 
-if [ -e "$pgmout" ] ; then
-  cat $pgmout
-fi
-
-##############################
+#############################
 # Remove the Temporary working directory
 ##############################
 cd $DATAROOT
 if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
 
-echo "$(date) $0 $(date -u) end"
+echo "$(date -u) end ${.sh.file}"
 
 exit $err
