Modify gefs_getcfssst task's j-job, script Modify setbase and gefs_config for gefs_getcfssst  Changes to be committed: 	modified:   jobs/JGEFS_GETCFSSST 	modified:   rocoto_new/parm/gefs_config 	modified:   rocoto_new/parm/setbase 	modified:   scripts/exgefs_getcfssst.sh.ecf
Refs: #52964

diff --git a/jobs/JGEFS_GETCFSSST b/jobs/JGEFS_GETCFSSST
--- a/jobs/JGEFS_GETCFSSST
+++ b/jobs/JGEFS_GETCFSSST
@@ -78,13 +78,16 @@ if [[ $gfssource != prod ]]; then
     echo $COMINgfs
     echo $COMINcfs
 fi
-export COMINgfs=${COMINgfs:-$COMROOThps/gfs/prod/gfs.${PDY}}    #/$cyc
-export COMINcfs=${COMINcfs:-$COMROOTp1/cfs/prod/cfs/cfs.${PDY}/$cyc} #
-
+export COMINgfs=${COMINgfs:-$COMROOThps/gfs/prod/gfs.${PDY}}  
 if [ ! -d $COMINgfs ]; then
-    echo "FAILED: $COMINgfs does not exist!"
-    exit 50
+    export COMINgfs=${COMINgfs:-$COMROOThps/gfs/prod/gfs.${PDY}/$cyc}
+    if [ ! -d $COMINgfs ]; then
+        echo "FAILED: $COMINgfs does not exist!"
+        exit 50
+    fi
 fi
+
+export COMINcfs=${COMINcfs:-$COMROOTp1/cfs/prod/cfs/cfs.${PDY}/$cyc}
 if [ ! -d $COMINcfs ]; then
     echo "FAILED: $COMINcfs does not exist!"
     exit 51
